config/routes.rb
Rails.application.routes.draw do
  get 'redirect/to'
  get 'search' => 'searches#show'
  get 'tweets' => 'tweets#show'

  root 'searches#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/redirect_controller.rb
class RedirectController < ApplicationController
  def to
    url = params[:url] || ''
    if url.match(%r{^https?://twitter.com})
      redirect_to url
    else
      render text: 'error'
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # top page
  def index
    @json_path = 'public/assets/json/cute.json'
    render 'index', layout: false
  end

  # searched page
  def show
    tweets =
      if params[:screen_name].present? && params[:screen_name].match(/\A@?\w+\z/)
        screen_name = params[:screen_name].match(/\A@?(\w+)\z/)[1]
        @json_path = "public/assets/json/screen_name/#{screen_name}.json"
        client.user_timeline(screen_name).map(&:attrs)
      elsif params[:hashtag].present?
        hashtag = params[:hashtag].starts_with?('#') ? params[:hashtag][1..-1] : params[:hashtag]
        @json_path = "public/assets/json/hash_tag/#{URI.encode(hashtag)}.json"
        client.search("##{hashtag}")
      end

    if tweets.nil?
      return render text: 'You need to specify a screen_name or a hashtag.'
    end

    begin
      PhotosUpdater.new({tweets: tweets, json_path: @json_path}).run
    rescue => e
      logger.warn e.inspect
      raise e
    end

    @json_path = URI.encode(@json_path)

    render 'index', layout: false
  end

  private

  def client
    @client ||= ExTwitter.new(YAML.load_file(Rails.root.join('config/twitter.yml')))
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include TweetsHelper

  before_action :set_tweet, only: [:show]

  # detail of photo page
  def show
    @user = @tweet.user
    @photo =
      if params[:photo_id].present? && params[:photo_id].match(/\A\d+\z/) && @tweet.media?
        photo_id = params[:photo_id]
        photo = @tweet.media.find{|m| m.id == photo_id }
        @tweet.media.first if photo.nil?
      else
        Hashie::Mash.new(Hash.new(''))
      end
  end

  private

  def client
    @client ||= ExTwitter.new(YAML.load_file(Rails.root.join('config/twitter.yml')))
  end

  def set_tweet
    if params[:status_id].present? && params[:status_id].match(/\A\d+\z/)
      @tweet = client.status(params[:status_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/redirect_helper.rb
module RedirectHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  include Twitter::Autolink

  def phone_device?
    if agent.match(/iPhone/)
      true
    elsif agent.match(/Android/) && agent.match(/Mobile/)
      true
    else
      false
    end
  end

  def left_box_class
    if phone_device?
      'col-xs-12 col-sm-12 col-md-12 left-box'
    else
      'col-xs-12 col-sm-12 col-md-6 left-box'
    end
  end

  def right_box_class
    if phone_device?
      'col-xs-12 col-sm-12 col-md-12 right-box'
    else
      'col-xs-12 col-sm-12 col-md-6 right-box'
    end
  end

  def agent
    request.env["HTTP_USER_AGENT"]
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img alt="Brand" src="">
      </a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <!--<li><a href="#">Link</a></li>-->
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pin-up Selfie - Japanese cute girls on Twitter.</title>
  <%= stylesheet_link_tag '/assets/javascripts/bootstrap-3.3.2/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag '/assets/stylesheets/tweets.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '/assets/javascripts/bootstrap-3.3.2/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/redirect/to.html.haml
%h1 Redirect#to
%p Find me in app/views/redirect/to.html.haml

app/views/searches/_form.html.haml
= form_for @search do |f|
  - if @search.errors.any?
    #error_explanation
      %h2= "#{pluralize(@search.errors.count, "error")} prohibited this search from being saved:"
      %ul
        - @search.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/searches/edit.html.haml
%h1 Editing search

= render 'form'

= link_to 'Show', @search
\|
= link_to 'Back', searches_path

app/views/searches/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>Pin-up Selfie - Japanese cute girls on Twitter.</title>
  <link rel="stylesheet" type="text/css" href="assets/stylesheets/application.css">
</head>
<body>
<div id="main">
  <noscript>
    <div>Please enable JavaScript in your browser and reload this page.</div>
  </noscript>
</div>
<script>
  window.json_url = '<%= @json_path.remove(%r{^public/}) %>';
</script>
<script src="assets/javascripts/json2.js"></script>
<script src="assets/javascripts/underscore-1.7.0.min.js"></script>
<script src="assets/javascripts/jquery-1.11.1.min.js"></script>
<script src="assets/javascripts/jquery.qtip-2.2.1.min.js"></script>
<script src="assets/javascripts/application.js"></script>
</body>
</html>

app/views/searches/new.html.haml
%h1 New search

= render 'form'

= link_to 'Back', searches_path

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', @tweet
\|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
%h1 Listing tweets

%table
  %thead
    %tr
      %th
      %th
      %th
      
  %tbody
    - @tweets.each do |tweet|
      %tr
        %td= link_to 'Show', tweet
        %td= link_to 'Edit', edit_tweet_path(tweet)
        %td= link_to 'Destroy', tweet, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tweet', new_tweet_path

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice

.container
  .row
    %div{class: left_box_class}
      .photo
        %img{src: @photo.media_url}
    %div{class: right_box_class}
      %div
        %img{src: @user.profile_image_url}
        = link_to "@#{@user.screen_name}", "https://twitter.com/#{@user.screen_name}"
        &nbsp;
        = "#{@user.name}"
      %div
        = auto_link(@tweet.text).html_safe
      %div
        = link_to time_ago_in_words(@tweet.created_at), "https://twitter.com/#{@user.screen_name}/status/#{@tweet.id}"
      .row(style="font-size: 10px;")
        .col-sm-2
          RETWEETS<br>
          = "<span style='font-size: 18px;'>#{@tweet.retweet_count}</span>".html_safe
        .col-sm-2
          FAVORITES<br>
          = "<span style='font-size: 18px;'>#{@tweet.favorite_count}</span>".html_safe
        .col-sm-8
      %hr
      %div
        = button_to "Search @#{@user.screen_name}", search_path(screen_name: @user.screen_name), class: 'btn btn-default'
      %div
        - if @tweet.hashtags?
          - @tweet.hashtags.each do |hashtag|
            = button_to "Search ##{hashtag.text}", search_path(hashtag: hashtag.text), class: 'btn btn-default'